"""QuizQuestionAnswer and QuizQuestionUserAnswer answer into number

Revision ID: 23e0ebe47c0c
Revises: 3cccd31290be
Create Date: 2025-03-13 15:48:54.580095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e0ebe47c0c'
down_revision = '3cccd31290be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_question_user_answers', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('quizz_question_ansers', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizz_question_ansers', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('quiz_question_user_answers', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
