"""Subjet topic reverse relation

Revision ID: 87a84c2e86e9
Revises: 4f6ad5592a1a
Create Date: 2025-03-10 11:01:48.792013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a84c2e86e9'
down_revision = '4f6ad5592a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('difficulty_level')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('difficulty_level', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
