"""Options

Revision ID: a8af39a517b4
Revises: 8d24f095541c
Create Date: 2025-03-13 12:41:14.842422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8af39a517b4'
down_revision = '8d24f095541c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option1', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('option2', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('option3', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('option4', sa.Text(), nullable=False))
        batch_op.drop_column('options')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', sa.BLOB(), nullable=False))
        batch_op.drop_column('option4')
        batch_op.drop_column('option3')
        batch_op.drop_column('option2')
        batch_op.drop_column('option1')

    # ### end Alembic commands ###
