"""QuizQuestionUserAnswer answer nullable

Revision ID: e19394e116bd
Revises: e1c3d3cbab68
Create Date: 2025-03-17 12:40:24.096101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19394e116bd'
down_revision = 'e1c3d3cbab68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_question_user_answers', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_question_user_answers', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
