"""QuizQuestionUserAnswer table

Revision ID: e1c3d3cbab68
Revises: ef5346a52c63
Create Date: 2025-03-17 12:27:13.058147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c3d3cbab68'
down_revision = 'ef5346a52c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_question_user_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_question_user_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_question_user_answers_question_id'), ['question_id'], unique=False)

    with op.batch_alter_table('quiz_question_answer', schema=None) as batch_op:
        batch_op.drop_index('ix_quiz_question_answer_question_id')
        batch_op.create_index(batch_op.f('ix_quiz_question_answer_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_question_answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_question_answer_question_id'))
        batch_op.create_index('ix_quiz_question_answer_question_id', ['question_id'], unique=1)

    with op.batch_alter_table('quiz_question_user_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_question_user_answers_question_id'))

    op.drop_table('quiz_question_user_answers')
    # ### end Alembic commands ###
