"""QuizQuestionAnswer table

Revision ID: ef5346a52c63
Revises: ffb12eac5432
Create Date: 2025-03-17 11:22:31.940367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5346a52c63'
down_revision = 'ffb12eac5432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_question_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option', sa.Enum(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_question_answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_question_answer_question_id'), ['question_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_quiz_question_answer_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_question_answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_question_answer_timestamp'))
        batch_op.drop_index(batch_op.f('ix_quiz_question_answer_question_id'))

    op.drop_table('quiz_question_answer')
    # ### end Alembic commands ###
